[package]
name = "text-ui"
version = "0.1.0"
authors = ["Stephen Weeks <tene@allalone.org>"]

[dependencies]
termion = "*"
unicode-segmentation = "1.2"
signal-hook = "0.1.3"
libc = "0.2"
itertools = "0.7"