[package]
name = "text-ui"
version = "0.1.0"
authors = ["Stephen Weeks <tene@allalone.org>"]

[dependencies]
termion = "1.5.1"
unicode-segmentation = "1.2"
signal-hook = "0.1.4"
libc = "0.2"
itertools = "0.7"
log = "0.4.5"

[dev-dependencies]
tempdir = "0.3.7"