[package]
name = "text-ui"
version = "0.1.0"
authors = ["Stephen Weeks <tene@allalone.org>"]

[dependencies]
unicode-segmentation = "1.2"
termion = "1.5.1"
log = "*"
libc = "*"

[dev-dependencies]
tempdir = "*"