[package]
name = "text-ui"
version = "0.1.0"
authors = ["Stephen Weeks <tene@allalone.org>"]

[dependencies]
unicode-segmentation = "1.2"
ggez = "*"

[patch.crates-io]
app_dirs = { git = "https://github.com/koute/app-dirs-rs" }